### ISSUE TITLE
Request for presence

### ISSUE THREAD

**Issue by ctubio** [abr4xas/sks-web#1]
Hello @abr4xas,
im collecting somehow web interfaces for keyservers, and i found yours very nice!

Therefore i was wondering if you let me add your project https://github.com/abr4xas/sks-web as a git submodule in https://github.com/ctubio/php-proxy-keyserver/tree/master/skin?

Otherwise i can add a text file with a link to your project (nice plan b)
Or otherwise, i can just do nothing (nice plan c)

What do you think?

Thank you for your time,

**Comment by abr4xas** [comment]
Hey @ctubio, no problem... You can add my project as a git submodule :D

**Comment by ctubio** [comment]
Thank you (alot!) @abr4xas :o]]]
and happy Regards from Catalonia,
